//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULIMSWcfClient.svcSpErf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErfData", Namespace="http://schemas.datacontract.org/2004/07/ULIMS.WCF.SP")]
    [System.SerializableAttribute()]
    public partial class ErfData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ComputedSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DensityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErfNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GlobalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ULIMSWcfClient.svcSpErf.ObjectState ItemStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastEditDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalAuthorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StandNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SurveySizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoningField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ComputedSize {
            get {
                return this.ComputedSizeField;
            }
            set {
                if ((this.ComputedSizeField.Equals(value) != true)) {
                    this.ComputedSizeField = value;
                    this.RaisePropertyChanged("ComputedSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Density {
            get {
                return this.DensityField;
            }
            set {
                if ((object.ReferenceEquals(this.DensityField, value) != true)) {
                    this.DensityField = value;
                    this.RaisePropertyChanged("Density");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErfNo {
            get {
                return this.ErfNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErfNoField, value) != true)) {
                    this.ErfNoField = value;
                    this.RaisePropertyChanged("ErfNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GlobalId {
            get {
                return this.GlobalIdField;
            }
            set {
                if ((this.GlobalIdField.Equals(value) != true)) {
                    this.GlobalIdField = value;
                    this.RaisePropertyChanged("GlobalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ULIMSWcfClient.svcSpErf.ObjectState ItemState {
            get {
                return this.ItemStateField;
            }
            set {
                if ((this.ItemStateField.Equals(value) != true)) {
                    this.ItemStateField = value;
                    this.RaisePropertyChanged("ItemState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastEditDate {
            get {
                return this.LastEditDateField;
            }
            set {
                if ((this.LastEditDateField.Equals(value) != true)) {
                    this.LastEditDateField = value;
                    this.RaisePropertyChanged("LastEditDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalAuthority {
            get {
                return this.LocalAuthorityField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalAuthorityField, value) != true)) {
                    this.LocalAuthorityField = value;
                    this.RaisePropertyChanged("LocalAuthority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ownership {
            get {
                return this.OwnershipField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnershipField, value) != true)) {
                    this.OwnershipField = value;
                    this.RaisePropertyChanged("Ownership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Portion {
            get {
                return this.PortionField;
            }
            set {
                if ((object.ReferenceEquals(this.PortionField, value) != true)) {
                    this.PortionField = value;
                    this.RaisePropertyChanged("Portion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StandNo {
            get {
                return this.StandNoField;
            }
            set {
                if ((object.ReferenceEquals(this.StandNoField, value) != true)) {
                    this.StandNoField = value;
                    this.RaisePropertyChanged("StandNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SurveySize {
            get {
                return this.SurveySizeField;
            }
            set {
                if ((this.SurveySizeField.Equals(value) != true)) {
                    this.SurveySizeField = value;
                    this.RaisePropertyChanged("SurveySize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Township {
            get {
                return this.TownshipField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipField, value) != true)) {
                    this.TownshipField = value;
                    this.RaisePropertyChanged("Township");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zoning {
            get {
                return this.ZoningField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoningField, value) != true)) {
                    this.ZoningField = value;
                    this.RaisePropertyChanged("Zoning");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/ULIMS.WCF.SP")]
    public enum ObjectState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ignore = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcSpErf.IErf")]
    public interface IErf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/Ping", ReplyAction="http://tempuri.org/ISync/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/Ping", ReplyAction="http://tempuri.org/ISync/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncGisToSpOf_ErfData/SaveRecords", ReplyAction="http://tempuri.org/ISyncGisToSpOf_ErfData/SaveRecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISyncGisToSpOf_ErfData/SaveRecordsExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool SaveRecords(ULIMSWcfClient.svcSpErf.ErfData[] items, string localAuthority, ULIMSWcfClient.svcSpErf.ObjectState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncGisToSpOf_ErfData/SaveRecords", ReplyAction="http://tempuri.org/ISyncGisToSpOf_ErfData/SaveRecordsResponse")]
        System.Threading.Tasks.Task<bool> SaveRecordsAsync(ULIMSWcfClient.svcSpErf.ErfData[] items, string localAuthority, ULIMSWcfClient.svcSpErf.ObjectState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSpToNavOf_ErfData/GetRecords", ReplyAction="http://tempuri.org/ISyncSpToNavOf_ErfData/GetRecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISyncSpToNavOf_ErfData/GetRecordsExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ULIMSWcfClient.svcSpErf.ErfData[] GetRecords(string localAuthority, int maximumRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSpToNavOf_ErfData/GetRecords", ReplyAction="http://tempuri.org/ISyncSpToNavOf_ErfData/GetRecordsResponse")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcSpErf.ErfData[]> GetRecordsAsync(string localAuthority, int maximumRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSpToNavOf_ErfData/FlagSynchronizedRecords", ReplyAction="http://tempuri.org/ISyncSpToNavOf_ErfData/FlagSynchronizedRecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISyncSpToNavOf_ErfData/FlagSynchronizedRecordsExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void FlagSynchronizedRecords(string localAuthority, int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSpToNavOf_ErfData/FlagSynchronizedRecords", ReplyAction="http://tempuri.org/ISyncSpToNavOf_ErfData/FlagSynchronizedRecordsResponse")]
        System.Threading.Tasks.Task FlagSynchronizedRecordsAsync(string localAuthority, int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErf/DeleteErfs", ReplyAction="http://tempuri.org/IErf/DeleteErfsResponse")]
        bool DeleteErfs(string localAuthorityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErf/DeleteErfs", ReplyAction="http://tempuri.org/IErf/DeleteErfsResponse")]
        System.Threading.Tasks.Task<bool> DeleteErfsAsync(string localAuthorityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErf/GetSiteUrl", ReplyAction="http://tempuri.org/IErf/GetSiteUrlResponse")]
        string GetSiteUrl(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErf/GetSiteUrl", ReplyAction="http://tempuri.org/IErf/GetSiteUrlResponse")]
        System.Threading.Tasks.Task<string> GetSiteUrlAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErf/GetRecordsByState", ReplyAction="http://tempuri.org/IErf/GetRecordsByStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IErf/GetRecordsByStateExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ULIMSWcfClient.svcSpErf.ErfData[] GetRecordsByState(string localAuthority, int maximumRows, ULIMSWcfClient.svcSpErf.ObjectState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErf/GetRecordsByState", ReplyAction="http://tempuri.org/IErf/GetRecordsByStateResponse")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcSpErf.ErfData[]> GetRecordsByStateAsync(string localAuthority, int maximumRows, ULIMSWcfClient.svcSpErf.ObjectState state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErfChannel : ULIMSWcfClient.svcSpErf.IErf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErfClient : System.ServiceModel.ClientBase<ULIMSWcfClient.svcSpErf.IErf>, ULIMSWcfClient.svcSpErf.IErf {
        
        public ErfClient() {
        }
        
        public ErfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public bool SaveRecords(ULIMSWcfClient.svcSpErf.ErfData[] items, string localAuthority, ULIMSWcfClient.svcSpErf.ObjectState state) {
            return base.Channel.SaveRecords(items, localAuthority, state);
        }
        
        public System.Threading.Tasks.Task<bool> SaveRecordsAsync(ULIMSWcfClient.svcSpErf.ErfData[] items, string localAuthority, ULIMSWcfClient.svcSpErf.ObjectState state) {
            return base.Channel.SaveRecordsAsync(items, localAuthority, state);
        }
        
        public ULIMSWcfClient.svcSpErf.ErfData[] GetRecords(string localAuthority, int maximumRows) {
            return base.Channel.GetRecords(localAuthority, maximumRows);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcSpErf.ErfData[]> GetRecordsAsync(string localAuthority, int maximumRows) {
            return base.Channel.GetRecordsAsync(localAuthority, maximumRows);
        }
        
        public void FlagSynchronizedRecords(string localAuthority, int[] ids) {
            base.Channel.FlagSynchronizedRecords(localAuthority, ids);
        }
        
        public System.Threading.Tasks.Task FlagSynchronizedRecordsAsync(string localAuthority, int[] ids) {
            return base.Channel.FlagSynchronizedRecordsAsync(localAuthority, ids);
        }
        
        public bool DeleteErfs(string localAuthorityCode) {
            return base.Channel.DeleteErfs(localAuthorityCode);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteErfsAsync(string localAuthorityCode) {
            return base.Channel.DeleteErfsAsync(localAuthorityCode);
        }
        
        public string GetSiteUrl(string code) {
            return base.Channel.GetSiteUrl(code);
        }
        
        public System.Threading.Tasks.Task<string> GetSiteUrlAsync(string code) {
            return base.Channel.GetSiteUrlAsync(code);
        }
        
        public ULIMSWcfClient.svcSpErf.ErfData[] GetRecordsByState(string localAuthority, int maximumRows, ULIMSWcfClient.svcSpErf.ObjectState state) {
            return base.Channel.GetRecordsByState(localAuthority, maximumRows, state);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcSpErf.ErfData[]> GetRecordsByStateAsync(string localAuthority, int maximumRows, ULIMSWcfClient.svcSpErf.ObjectState state) {
            return base.Channel.GetRecordsByStateAsync(localAuthority, maximumRows, state);
        }
    }
}
