//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULIMSWcfClient.svcNavCharges {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", ConfigurationName="svcNavCharges.Charges_Port")]
    public interface Charges_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.Read_Result Read(ULIMSWcfClient.svcNavCharges.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Read_Result> ReadAsync(ULIMSWcfClient.svcNavCharges.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.ReadByRecId_Result ReadByRecId(ULIMSWcfClient.svcNavCharges.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.ReadByRecId_Result> ReadByRecIdAsync(ULIMSWcfClient.svcNavCharges.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.ReadMultiple_Result ReadMultiple(ULIMSWcfClient.svcNavCharges.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavCharges.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.IsUpdated_Result IsUpdated(ULIMSWcfClient.svcNavCharges.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.IsUpdated_Result> IsUpdatedAsync(ULIMSWcfClient.svcNavCharges.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.GetRecIdFromKey_Result GetRecIdFromKey(ULIMSWcfClient.svcNavCharges.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavCharges.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.Create_Result Create(ULIMSWcfClient.svcNavCharges.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Create_Result> CreateAsync(ULIMSWcfClient.svcNavCharges.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.CreateMultiple_Result CreateMultiple(ULIMSWcfClient.svcNavCharges.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavCharges.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.Update_Result Update(ULIMSWcfClient.svcNavCharges.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavCharges.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.UpdateMultiple_Result UpdateMultiple(ULIMSWcfClient.svcNavCharges.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavCharges.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavCharges.Delete_Result Delete(ULIMSWcfClient.svcNavCharges.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/charges:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Delete_Result> DeleteAsync(ULIMSWcfClient.svcNavCharges.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges")]
    public partial class Charges : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string reference_NoField;
        
        private string descriptionField;
        
        private bool vAT_AppliesField;
        
        private bool vAT_AppliesFieldSpecified;
        
        private decimal amount_Exclusive_VATField;
        
        private bool amount_Exclusive_VATFieldSpecified;
        
        private string vAT_Prod_Posting_GroupField;
        
        private decimal vAT_AmountField;
        
        private bool vAT_AmountFieldSpecified;
        
        private decimal total_AmountField;
        
        private bool total_AmountFieldSpecified;
        
        private System.DateTime due_DateField;
        
        private bool due_DateFieldSpecified;
        
        private string stand_NoField;
        
        private string charge_TypeField;
        
        private string application_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reference_No {
            get {
                return this.reference_NoField;
            }
            set {
                this.reference_NoField = value;
                this.RaisePropertyChanged("Reference_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VAT_Applies?", Order=3)]
        public bool VAT_Applies {
            get {
                return this.vAT_AppliesField;
            }
            set {
                this.vAT_AppliesField = value;
                this.RaisePropertyChanged("VAT_Applies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_AppliesSpecified {
            get {
                return this.vAT_AppliesFieldSpecified;
            }
            set {
                this.vAT_AppliesFieldSpecified = value;
                this.RaisePropertyChanged("VAT_AppliesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Amount_Exclusive_VAT {
            get {
                return this.amount_Exclusive_VATField;
            }
            set {
                this.amount_Exclusive_VATField = value;
                this.RaisePropertyChanged("Amount_Exclusive_VAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_Exclusive_VATSpecified {
            get {
                return this.amount_Exclusive_VATFieldSpecified;
            }
            set {
                this.amount_Exclusive_VATFieldSpecified = value;
                this.RaisePropertyChanged("Amount_Exclusive_VATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string VAT_Prod_Posting_Group {
            get {
                return this.vAT_Prod_Posting_GroupField;
            }
            set {
                this.vAT_Prod_Posting_GroupField = value;
                this.RaisePropertyChanged("VAT_Prod_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal VAT_Amount {
            get {
                return this.vAT_AmountField;
            }
            set {
                this.vAT_AmountField = value;
                this.RaisePropertyChanged("VAT_Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_AmountSpecified {
            get {
                return this.vAT_AmountFieldSpecified;
            }
            set {
                this.vAT_AmountFieldSpecified = value;
                this.RaisePropertyChanged("VAT_AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Total_Amount {
            get {
                return this.total_AmountField;
            }
            set {
                this.total_AmountField = value;
                this.RaisePropertyChanged("Total_Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_AmountSpecified {
            get {
                return this.total_AmountFieldSpecified;
            }
            set {
                this.total_AmountFieldSpecified = value;
                this.RaisePropertyChanged("Total_AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime Due_Date {
            get {
                return this.due_DateField;
            }
            set {
                this.due_DateField = value;
                this.RaisePropertyChanged("Due_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Due_DateSpecified {
            get {
                return this.due_DateFieldSpecified;
            }
            set {
                this.due_DateFieldSpecified = value;
                this.RaisePropertyChanged("Due_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Stand_No {
            get {
                return this.stand_NoField;
            }
            set {
                this.stand_NoField = value;
                this.RaisePropertyChanged("Stand_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Charge_Type {
            get {
                return this.charge_TypeField;
            }
            set {
                this.charge_TypeField = value;
                this.RaisePropertyChanged("Charge_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Application_ID {
            get {
                return this.application_IDField;
            }
            set {
                this.application_IDField = value;
                this.RaisePropertyChanged("Application_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges")]
    public partial class Charges_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Charges_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Charges_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges")]
    public enum Charges_Fields {
        
        /// <remarks/>
        Reference_No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        VAT_Applies_x003F_,
        
        /// <remarks/>
        Amount_Exclusive_VAT,
        
        /// <remarks/>
        VAT_Prod_Posting_Group,
        
        /// <remarks/>
        VAT_Amount,
        
        /// <remarks/>
        Total_Amount,
        
        /// <remarks/>
        Due_Date,
        
        /// <remarks/>
        Stand_No,
        
        /// <remarks/>
        Charge_Type,
        
        /// <remarks/>
        Application_ID,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public string Reference_No;
        
        public Read() {
        }
        
        public Read(string Reference_No) {
            this.Reference_No = Reference_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public ULIMSWcfClient.svcNavCharges.Charges Charges;
        
        public Read_Result() {
        }
        
        public Read_Result(ULIMSWcfClient.svcNavCharges.Charges Charges) {
            this.Charges = Charges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public ULIMSWcfClient.svcNavCharges.Charges Charges;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ULIMSWcfClient.svcNavCharges.Charges Charges) {
            this.Charges = Charges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ULIMSWcfClient.svcNavCharges.Charges_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ULIMSWcfClient.svcNavCharges.Charges_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavCharges.Charges[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ULIMSWcfClient.svcNavCharges.Charges[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public ULIMSWcfClient.svcNavCharges.Charges Charges;
        
        public Create() {
        }
        
        public Create(ULIMSWcfClient.svcNavCharges.Charges Charges) {
            this.Charges = Charges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public ULIMSWcfClient.svcNavCharges.Charges Charges;
        
        public Create_Result() {
        }
        
        public Create_Result(ULIMSWcfClient.svcNavCharges.Charges Charges) {
            this.Charges = Charges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavCharges.Charges[] Charges_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ULIMSWcfClient.svcNavCharges.Charges[] Charges_List) {
            this.Charges_List = Charges_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavCharges.Charges[] Charges_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ULIMSWcfClient.svcNavCharges.Charges[] Charges_List) {
            this.Charges_List = Charges_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public ULIMSWcfClient.svcNavCharges.Charges Charges;
        
        public Update() {
        }
        
        public Update(ULIMSWcfClient.svcNavCharges.Charges Charges) {
            this.Charges = Charges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public ULIMSWcfClient.svcNavCharges.Charges Charges;
        
        public Update_Result() {
        }
        
        public Update_Result(ULIMSWcfClient.svcNavCharges.Charges Charges) {
            this.Charges = Charges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavCharges.Charges[] Charges_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ULIMSWcfClient.svcNavCharges.Charges[] Charges_List) {
            this.Charges_List = Charges_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavCharges.Charges[] Charges_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ULIMSWcfClient.svcNavCharges.Charges[] Charges_List) {
            this.Charges_List = Charges_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/charges", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/charges", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Charges_PortChannel : ULIMSWcfClient.svcNavCharges.Charges_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Charges_PortClient : System.ServiceModel.ClientBase<ULIMSWcfClient.svcNavCharges.Charges_Port>, ULIMSWcfClient.svcNavCharges.Charges_Port {
        
        public Charges_PortClient() {
        }
        
        public Charges_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Charges_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Charges_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Charges_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.Read_Result ULIMSWcfClient.svcNavCharges.Charges_Port.Read(ULIMSWcfClient.svcNavCharges.Read request) {
            return base.Channel.Read(request);
        }
        
        public ULIMSWcfClient.svcNavCharges.Charges Read(string Reference_No) {
            ULIMSWcfClient.svcNavCharges.Read inValue = new ULIMSWcfClient.svcNavCharges.Read();
            inValue.Reference_No = Reference_No;
            ULIMSWcfClient.svcNavCharges.Read_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).Read(inValue);
            return retVal.Charges;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Read_Result> ULIMSWcfClient.svcNavCharges.Charges_Port.ReadAsync(ULIMSWcfClient.svcNavCharges.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Read_Result> ReadAsync(string Reference_No) {
            ULIMSWcfClient.svcNavCharges.Read inValue = new ULIMSWcfClient.svcNavCharges.Read();
            inValue.Reference_No = Reference_No;
            return ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.ReadByRecId_Result ULIMSWcfClient.svcNavCharges.Charges_Port.ReadByRecId(ULIMSWcfClient.svcNavCharges.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ULIMSWcfClient.svcNavCharges.Charges ReadByRecId(string recId) {
            ULIMSWcfClient.svcNavCharges.ReadByRecId inValue = new ULIMSWcfClient.svcNavCharges.ReadByRecId();
            inValue.recId = recId;
            ULIMSWcfClient.svcNavCharges.ReadByRecId_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).ReadByRecId(inValue);
            return retVal.Charges;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.ReadByRecId_Result> ULIMSWcfClient.svcNavCharges.Charges_Port.ReadByRecIdAsync(ULIMSWcfClient.svcNavCharges.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ULIMSWcfClient.svcNavCharges.ReadByRecId inValue = new ULIMSWcfClient.svcNavCharges.ReadByRecId();
            inValue.recId = recId;
            return ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.ReadMultiple_Result ULIMSWcfClient.svcNavCharges.Charges_Port.ReadMultiple(ULIMSWcfClient.svcNavCharges.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ULIMSWcfClient.svcNavCharges.Charges[] ReadMultiple(ULIMSWcfClient.svcNavCharges.Charges_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavCharges.ReadMultiple inValue = new ULIMSWcfClient.svcNavCharges.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ULIMSWcfClient.svcNavCharges.ReadMultiple_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.ReadMultiple_Result> ULIMSWcfClient.svcNavCharges.Charges_Port.ReadMultipleAsync(ULIMSWcfClient.svcNavCharges.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavCharges.Charges_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavCharges.ReadMultiple inValue = new ULIMSWcfClient.svcNavCharges.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.IsUpdated_Result ULIMSWcfClient.svcNavCharges.Charges_Port.IsUpdated(ULIMSWcfClient.svcNavCharges.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ULIMSWcfClient.svcNavCharges.IsUpdated inValue = new ULIMSWcfClient.svcNavCharges.IsUpdated();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavCharges.IsUpdated_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.IsUpdated_Result> ULIMSWcfClient.svcNavCharges.Charges_Port.IsUpdatedAsync(ULIMSWcfClient.svcNavCharges.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ULIMSWcfClient.svcNavCharges.IsUpdated inValue = new ULIMSWcfClient.svcNavCharges.IsUpdated();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.GetRecIdFromKey_Result ULIMSWcfClient.svcNavCharges.Charges_Port.GetRecIdFromKey(ULIMSWcfClient.svcNavCharges.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ULIMSWcfClient.svcNavCharges.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavCharges.GetRecIdFromKey();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavCharges.GetRecIdFromKey_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.GetRecIdFromKey_Result> ULIMSWcfClient.svcNavCharges.Charges_Port.GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavCharges.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ULIMSWcfClient.svcNavCharges.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavCharges.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.Create_Result ULIMSWcfClient.svcNavCharges.Charges_Port.Create(ULIMSWcfClient.svcNavCharges.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ULIMSWcfClient.svcNavCharges.Charges Charges) {
            ULIMSWcfClient.svcNavCharges.Create inValue = new ULIMSWcfClient.svcNavCharges.Create();
            inValue.Charges = Charges;
            ULIMSWcfClient.svcNavCharges.Create_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).Create(inValue);
            Charges = retVal.Charges;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Create_Result> CreateAsync(ULIMSWcfClient.svcNavCharges.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.CreateMultiple_Result ULIMSWcfClient.svcNavCharges.Charges_Port.CreateMultiple(ULIMSWcfClient.svcNavCharges.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ULIMSWcfClient.svcNavCharges.Charges[] Charges_List) {
            ULIMSWcfClient.svcNavCharges.CreateMultiple inValue = new ULIMSWcfClient.svcNavCharges.CreateMultiple();
            inValue.Charges_List = Charges_List;
            ULIMSWcfClient.svcNavCharges.CreateMultiple_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).CreateMultiple(inValue);
            Charges_List = retVal.Charges_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavCharges.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.Update_Result ULIMSWcfClient.svcNavCharges.Charges_Port.Update(ULIMSWcfClient.svcNavCharges.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ULIMSWcfClient.svcNavCharges.Charges Charges) {
            ULIMSWcfClient.svcNavCharges.Update inValue = new ULIMSWcfClient.svcNavCharges.Update();
            inValue.Charges = Charges;
            ULIMSWcfClient.svcNavCharges.Update_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).Update(inValue);
            Charges = retVal.Charges;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavCharges.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.UpdateMultiple_Result ULIMSWcfClient.svcNavCharges.Charges_Port.UpdateMultiple(ULIMSWcfClient.svcNavCharges.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ULIMSWcfClient.svcNavCharges.Charges[] Charges_List) {
            ULIMSWcfClient.svcNavCharges.UpdateMultiple inValue = new ULIMSWcfClient.svcNavCharges.UpdateMultiple();
            inValue.Charges_List = Charges_List;
            ULIMSWcfClient.svcNavCharges.UpdateMultiple_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).UpdateMultiple(inValue);
            Charges_List = retVal.Charges_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavCharges.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavCharges.Delete_Result ULIMSWcfClient.svcNavCharges.Charges_Port.Delete(ULIMSWcfClient.svcNavCharges.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ULIMSWcfClient.svcNavCharges.Delete inValue = new ULIMSWcfClient.svcNavCharges.Delete();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavCharges.Delete_Result retVal = ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Delete_Result> ULIMSWcfClient.svcNavCharges.Charges_Port.DeleteAsync(ULIMSWcfClient.svcNavCharges.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavCharges.Delete_Result> DeleteAsync(string Key) {
            ULIMSWcfClient.svcNavCharges.Delete inValue = new ULIMSWcfClient.svcNavCharges.Delete();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavCharges.Charges_Port)(this)).DeleteAsync(inValue);
        }
    }
}
