//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULIMSWcfClient.svcNavValuationPeriods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", ConfigurationName="svcNavValuationPeriods.Valuationperiods_Port")]
    public interface Valuationperiods_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.Read_Result Read(ULIMSWcfClient.svcNavValuationPeriods.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Read_Result> ReadAsync(ULIMSWcfClient.svcNavValuationPeriods.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId_Result ReadByRecId(ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId_Result> ReadByRecIdAsync(ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple_Result ReadMultiple(ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.IsUpdated_Result IsUpdated(ULIMSWcfClient.svcNavValuationPeriods.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.IsUpdated_Result> IsUpdatedAsync(ULIMSWcfClient.svcNavValuationPeriods.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey_Result GetRecIdFromKey(ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.Create_Result Create(ULIMSWcfClient.svcNavValuationPeriods.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Create_Result> CreateAsync(ULIMSWcfClient.svcNavValuationPeriods.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple_Result CreateMultiple(ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.Update_Result Update(ULIMSWcfClient.svcNavValuationPeriods.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavValuationPeriods.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple_Result UpdateMultiple(ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuationPeriods.Delete_Result Delete(ULIMSWcfClient.svcNavValuationPeriods.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuationperiods:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Delete_Result> DeleteAsync(ULIMSWcfClient.svcNavValuationPeriods.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods")]
    public partial class Valuationperiods : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string request_IDField;
        
        private string period_NameField;
        
        private string valuation_TypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Request_ID {
            get {
                return this.request_IDField;
            }
            set {
                this.request_IDField = value;
                this.RaisePropertyChanged("Request_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Period_Name {
            get {
                return this.period_NameField;
            }
            set {
                this.period_NameField = value;
                this.RaisePropertyChanged("Period_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Valuation_Type {
            get {
                return this.valuation_TypeField;
            }
            set {
                this.valuation_TypeField = value;
                this.RaisePropertyChanged("Valuation_Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods")]
    public partial class Valuationperiods_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Valuationperiods_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Valuationperiods_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods")]
    public enum Valuationperiods_Fields {
        
        /// <remarks/>
        Request_ID,
        
        /// <remarks/>
        Period_Name,
        
        /// <remarks/>
        Valuation_Type,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public string Request_ID;
        
        public Read() {
        }
        
        public Read(string Request_ID) {
            this.Request_ID = Request_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods;
        
        public Read_Result() {
        }
        
        public Read_Result(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            this.Valuationperiods = Valuationperiods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            this.Valuationperiods = Valuationperiods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods;
        
        public Create() {
        }
        
        public Create(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            this.Valuationperiods = Valuationperiods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods;
        
        public Create_Result() {
        }
        
        public Create_Result(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            this.Valuationperiods = Valuationperiods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List) {
            this.Valuationperiods_List = Valuationperiods_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List) {
            this.Valuationperiods_List = Valuationperiods_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods;
        
        public Update() {
        }
        
        public Update(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            this.Valuationperiods = Valuationperiods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods;
        
        public Update_Result() {
        }
        
        public Update_Result(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            this.Valuationperiods = Valuationperiods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List) {
            this.Valuationperiods_List = Valuationperiods_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List) {
            this.Valuationperiods_List = Valuationperiods_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuationperiods", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuationperiods", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Valuationperiods_PortChannel : ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Valuationperiods_PortClient : System.ServiceModel.ClientBase<ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port>, ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port {
        
        public Valuationperiods_PortClient() {
        }
        
        public Valuationperiods_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Valuationperiods_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Valuationperiods_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Valuationperiods_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.Read_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.Read(ULIMSWcfClient.svcNavValuationPeriods.Read request) {
            return base.Channel.Read(request);
        }
        
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Read(string Request_ID) {
            ULIMSWcfClient.svcNavValuationPeriods.Read inValue = new ULIMSWcfClient.svcNavValuationPeriods.Read();
            inValue.Request_ID = Request_ID;
            ULIMSWcfClient.svcNavValuationPeriods.Read_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).Read(inValue);
            return retVal.Valuationperiods;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Read_Result> ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.ReadAsync(ULIMSWcfClient.svcNavValuationPeriods.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Read_Result> ReadAsync(string Request_ID) {
            ULIMSWcfClient.svcNavValuationPeriods.Read inValue = new ULIMSWcfClient.svcNavValuationPeriods.Read();
            inValue.Request_ID = Request_ID;
            return ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.ReadByRecId(ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods ReadByRecId(string recId) {
            ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId inValue = new ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId();
            inValue.recId = recId;
            ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).ReadByRecId(inValue);
            return retVal.Valuationperiods;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId_Result> ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.ReadByRecIdAsync(ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId inValue = new ULIMSWcfClient.svcNavValuationPeriods.ReadByRecId();
            inValue.recId = recId;
            return ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.ReadMultiple(ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] ReadMultiple(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple inValue = new ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple_Result> ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.ReadMultipleAsync(ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple inValue = new ULIMSWcfClient.svcNavValuationPeriods.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.IsUpdated_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.IsUpdated(ULIMSWcfClient.svcNavValuationPeriods.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ULIMSWcfClient.svcNavValuationPeriods.IsUpdated inValue = new ULIMSWcfClient.svcNavValuationPeriods.IsUpdated();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavValuationPeriods.IsUpdated_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.IsUpdated_Result> ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.IsUpdatedAsync(ULIMSWcfClient.svcNavValuationPeriods.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ULIMSWcfClient.svcNavValuationPeriods.IsUpdated inValue = new ULIMSWcfClient.svcNavValuationPeriods.IsUpdated();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.GetRecIdFromKey(ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey_Result> ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavValuationPeriods.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.Create_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.Create(ULIMSWcfClient.svcNavValuationPeriods.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            ULIMSWcfClient.svcNavValuationPeriods.Create inValue = new ULIMSWcfClient.svcNavValuationPeriods.Create();
            inValue.Valuationperiods = Valuationperiods;
            ULIMSWcfClient.svcNavValuationPeriods.Create_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).Create(inValue);
            Valuationperiods = retVal.Valuationperiods;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Create_Result> CreateAsync(ULIMSWcfClient.svcNavValuationPeriods.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.CreateMultiple(ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List) {
            ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple inValue = new ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple();
            inValue.Valuationperiods_List = Valuationperiods_List;
            ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).CreateMultiple(inValue);
            Valuationperiods_List = retVal.Valuationperiods_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavValuationPeriods.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.Update_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.Update(ULIMSWcfClient.svcNavValuationPeriods.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods Valuationperiods) {
            ULIMSWcfClient.svcNavValuationPeriods.Update inValue = new ULIMSWcfClient.svcNavValuationPeriods.Update();
            inValue.Valuationperiods = Valuationperiods;
            ULIMSWcfClient.svcNavValuationPeriods.Update_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).Update(inValue);
            Valuationperiods = retVal.Valuationperiods;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavValuationPeriods.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.UpdateMultiple(ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods[] Valuationperiods_List) {
            ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple inValue = new ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple();
            inValue.Valuationperiods_List = Valuationperiods_List;
            ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).UpdateMultiple(inValue);
            Valuationperiods_List = retVal.Valuationperiods_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavValuationPeriods.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuationPeriods.Delete_Result ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.Delete(ULIMSWcfClient.svcNavValuationPeriods.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ULIMSWcfClient.svcNavValuationPeriods.Delete inValue = new ULIMSWcfClient.svcNavValuationPeriods.Delete();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavValuationPeriods.Delete_Result retVal = ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Delete_Result> ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port.DeleteAsync(ULIMSWcfClient.svcNavValuationPeriods.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuationPeriods.Delete_Result> DeleteAsync(string Key) {
            ULIMSWcfClient.svcNavValuationPeriods.Delete inValue = new ULIMSWcfClient.svcNavValuationPeriods.Delete();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavValuationPeriods.Valuationperiods_Port)(this)).DeleteAsync(inValue);
        }
    }
}
