//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULIMSWcfClient.svcNavValuation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", ConfigurationName="svcNavValuation.Valuation_Port")]
    public interface Valuation_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.Read_Result Read(ULIMSWcfClient.svcNavValuation.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Read_Result> ReadAsync(ULIMSWcfClient.svcNavValuation.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.ReadByRecId_Result ReadByRecId(ULIMSWcfClient.svcNavValuation.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.ReadByRecId_Result> ReadByRecIdAsync(ULIMSWcfClient.svcNavValuation.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.ReadMultiple_Result ReadMultiple(ULIMSWcfClient.svcNavValuation.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavValuation.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.IsUpdated_Result IsUpdated(ULIMSWcfClient.svcNavValuation.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.IsUpdated_Result> IsUpdatedAsync(ULIMSWcfClient.svcNavValuation.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.GetRecIdFromKey_Result GetRecIdFromKey(ULIMSWcfClient.svcNavValuation.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavValuation.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.Create_Result Create(ULIMSWcfClient.svcNavValuation.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Create_Result> CreateAsync(ULIMSWcfClient.svcNavValuation.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.CreateMultiple_Result CreateMultiple(ULIMSWcfClient.svcNavValuation.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavValuation.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.Update_Result Update(ULIMSWcfClient.svcNavValuation.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavValuation.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.UpdateMultiple_Result UpdateMultiple(ULIMSWcfClient.svcNavValuation.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavValuation.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavValuation.Delete_Result Delete(ULIMSWcfClient.svcNavValuation.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/valuation:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Delete_Result> DeleteAsync(ULIMSWcfClient.svcNavValuation.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation")]
    public partial class Valuation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private System.DateTime effective_DateField;
        
        private bool effective_DateFieldSpecified;
        
        private string stand_NoField;
        
        private decimal land_ValueField;
        
        private bool land_ValueFieldSpecified;
        
        private decimal improvement_ValueField;
        
        private bool improvement_ValueFieldSpecified;
        
        private string descriptionField;
        
        private string erf_NoField;
        
        private string townshipField;
        
        private decimal land_Value_Non_RateableField;
        
        private bool land_Value_Non_RateableFieldSpecified;
        
        private decimal improvement_Non_RateableField;
        
        private bool improvement_Non_RateableFieldSpecified;
        
        private string title_DateField;
        
        private string priceField;
        
        private string zoningField;
        
        private decimal areaField;
        
        private bool areaFieldSpecified;
        
        private string registered_OwnerField;
        
        private string street_AddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime Effective_Date {
            get {
                return this.effective_DateField;
            }
            set {
                this.effective_DateField = value;
                this.RaisePropertyChanged("Effective_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Effective_DateSpecified {
            get {
                return this.effective_DateFieldSpecified;
            }
            set {
                this.effective_DateFieldSpecified = value;
                this.RaisePropertyChanged("Effective_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Stand_No {
            get {
                return this.stand_NoField;
            }
            set {
                this.stand_NoField = value;
                this.RaisePropertyChanged("Stand_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Land_Value {
            get {
                return this.land_ValueField;
            }
            set {
                this.land_ValueField = value;
                this.RaisePropertyChanged("Land_Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Land_ValueSpecified {
            get {
                return this.land_ValueFieldSpecified;
            }
            set {
                this.land_ValueFieldSpecified = value;
                this.RaisePropertyChanged("Land_ValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Improvement_Value {
            get {
                return this.improvement_ValueField;
            }
            set {
                this.improvement_ValueField = value;
                this.RaisePropertyChanged("Improvement_Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Improvement_ValueSpecified {
            get {
                return this.improvement_ValueFieldSpecified;
            }
            set {
                this.improvement_ValueFieldSpecified = value;
                this.RaisePropertyChanged("Improvement_ValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Erf_No {
            get {
                return this.erf_NoField;
            }
            set {
                this.erf_NoField = value;
                this.RaisePropertyChanged("Erf_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Township {
            get {
                return this.townshipField;
            }
            set {
                this.townshipField = value;
                this.RaisePropertyChanged("Township");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Land_Value_Non_Rateable {
            get {
                return this.land_Value_Non_RateableField;
            }
            set {
                this.land_Value_Non_RateableField = value;
                this.RaisePropertyChanged("Land_Value_Non_Rateable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Land_Value_Non_RateableSpecified {
            get {
                return this.land_Value_Non_RateableFieldSpecified;
            }
            set {
                this.land_Value_Non_RateableFieldSpecified = value;
                this.RaisePropertyChanged("Land_Value_Non_RateableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Improvement_Non_Rateable {
            get {
                return this.improvement_Non_RateableField;
            }
            set {
                this.improvement_Non_RateableField = value;
                this.RaisePropertyChanged("Improvement_Non_Rateable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Improvement_Non_RateableSpecified {
            get {
                return this.improvement_Non_RateableFieldSpecified;
            }
            set {
                this.improvement_Non_RateableFieldSpecified = value;
                this.RaisePropertyChanged("Improvement_Non_RateableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Title_Date {
            get {
                return this.title_DateField;
            }
            set {
                this.title_DateField = value;
                this.RaisePropertyChanged("Title_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Zoning {
            get {
                return this.zoningField;
            }
            set {
                this.zoningField = value;
                this.RaisePropertyChanged("Zoning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AreaSpecified {
            get {
                return this.areaFieldSpecified;
            }
            set {
                this.areaFieldSpecified = value;
                this.RaisePropertyChanged("AreaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Registered_Owner {
            get {
                return this.registered_OwnerField;
            }
            set {
                this.registered_OwnerField = value;
                this.RaisePropertyChanged("Registered_Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Street_Address {
            get {
                return this.street_AddressField;
            }
            set {
                this.street_AddressField = value;
                this.RaisePropertyChanged("Street_Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation")]
    public partial class Valuation_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Valuation_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Valuation_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation")]
    public enum Valuation_Fields {
        
        /// <remarks/>
        Effective_Date,
        
        /// <remarks/>
        Stand_No,
        
        /// <remarks/>
        Land_Value,
        
        /// <remarks/>
        Improvement_Value,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Erf_No,
        
        /// <remarks/>
        Township,
        
        /// <remarks/>
        Land_Value_Non_Rateable,
        
        /// <remarks/>
        Improvement_Non_Rateable,
        
        /// <remarks/>
        Title_Date,
        
        /// <remarks/>
        Price,
        
        /// <remarks/>
        Zoning,
        
        /// <remarks/>
        Area,
        
        /// <remarks/>
        Registered_Owner,
        
        /// <remarks/>
        Street_Address,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public string Erf_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=1)]
        public string Township;
        
        public Read() {
        }
        
        public Read(string Erf_No, string Township) {
            this.Erf_No = Erf_No;
            this.Township = Township;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public ULIMSWcfClient.svcNavValuation.Valuation Valuation;
        
        public Read_Result() {
        }
        
        public Read_Result(ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            this.Valuation = Valuation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public ULIMSWcfClient.svcNavValuation.Valuation Valuation;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            this.Valuation = Valuation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ULIMSWcfClient.svcNavValuation.Valuation_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ULIMSWcfClient.svcNavValuation.Valuation_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuation.Valuation[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ULIMSWcfClient.svcNavValuation.Valuation[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public ULIMSWcfClient.svcNavValuation.Valuation Valuation;
        
        public Create() {
        }
        
        public Create(ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            this.Valuation = Valuation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public ULIMSWcfClient.svcNavValuation.Valuation Valuation;
        
        public Create_Result() {
        }
        
        public Create_Result(ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            this.Valuation = Valuation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List) {
            this.Valuation_List = Valuation_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List) {
            this.Valuation_List = Valuation_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public ULIMSWcfClient.svcNavValuation.Valuation Valuation;
        
        public Update() {
        }
        
        public Update(ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            this.Valuation = Valuation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public ULIMSWcfClient.svcNavValuation.Valuation Valuation;
        
        public Update_Result() {
        }
        
        public Update_Result(ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            this.Valuation = Valuation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List) {
            this.Valuation_List = Valuation_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List) {
            this.Valuation_List = Valuation_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/valuation", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/valuation", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Valuation_PortChannel : ULIMSWcfClient.svcNavValuation.Valuation_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Valuation_PortClient : System.ServiceModel.ClientBase<ULIMSWcfClient.svcNavValuation.Valuation_Port>, ULIMSWcfClient.svcNavValuation.Valuation_Port {
        
        public Valuation_PortClient() {
        }
        
        public Valuation_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Valuation_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Valuation_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Valuation_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.Read_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.Read(ULIMSWcfClient.svcNavValuation.Read request) {
            return base.Channel.Read(request);
        }
        
        public ULIMSWcfClient.svcNavValuation.Valuation Read(string Erf_No, string Township) {
            ULIMSWcfClient.svcNavValuation.Read inValue = new ULIMSWcfClient.svcNavValuation.Read();
            inValue.Erf_No = Erf_No;
            inValue.Township = Township;
            ULIMSWcfClient.svcNavValuation.Read_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).Read(inValue);
            return retVal.Valuation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Read_Result> ULIMSWcfClient.svcNavValuation.Valuation_Port.ReadAsync(ULIMSWcfClient.svcNavValuation.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Read_Result> ReadAsync(string Erf_No, string Township) {
            ULIMSWcfClient.svcNavValuation.Read inValue = new ULIMSWcfClient.svcNavValuation.Read();
            inValue.Erf_No = Erf_No;
            inValue.Township = Township;
            return ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.ReadByRecId_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.ReadByRecId(ULIMSWcfClient.svcNavValuation.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ULIMSWcfClient.svcNavValuation.Valuation ReadByRecId(string recId) {
            ULIMSWcfClient.svcNavValuation.ReadByRecId inValue = new ULIMSWcfClient.svcNavValuation.ReadByRecId();
            inValue.recId = recId;
            ULIMSWcfClient.svcNavValuation.ReadByRecId_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).ReadByRecId(inValue);
            return retVal.Valuation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.ReadByRecId_Result> ULIMSWcfClient.svcNavValuation.Valuation_Port.ReadByRecIdAsync(ULIMSWcfClient.svcNavValuation.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ULIMSWcfClient.svcNavValuation.ReadByRecId inValue = new ULIMSWcfClient.svcNavValuation.ReadByRecId();
            inValue.recId = recId;
            return ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.ReadMultiple_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.ReadMultiple(ULIMSWcfClient.svcNavValuation.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ULIMSWcfClient.svcNavValuation.Valuation[] ReadMultiple(ULIMSWcfClient.svcNavValuation.Valuation_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavValuation.ReadMultiple inValue = new ULIMSWcfClient.svcNavValuation.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ULIMSWcfClient.svcNavValuation.ReadMultiple_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.ReadMultiple_Result> ULIMSWcfClient.svcNavValuation.Valuation_Port.ReadMultipleAsync(ULIMSWcfClient.svcNavValuation.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavValuation.Valuation_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavValuation.ReadMultiple inValue = new ULIMSWcfClient.svcNavValuation.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.IsUpdated_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.IsUpdated(ULIMSWcfClient.svcNavValuation.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ULIMSWcfClient.svcNavValuation.IsUpdated inValue = new ULIMSWcfClient.svcNavValuation.IsUpdated();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavValuation.IsUpdated_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.IsUpdated_Result> ULIMSWcfClient.svcNavValuation.Valuation_Port.IsUpdatedAsync(ULIMSWcfClient.svcNavValuation.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ULIMSWcfClient.svcNavValuation.IsUpdated inValue = new ULIMSWcfClient.svcNavValuation.IsUpdated();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.GetRecIdFromKey_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.GetRecIdFromKey(ULIMSWcfClient.svcNavValuation.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ULIMSWcfClient.svcNavValuation.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavValuation.GetRecIdFromKey();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavValuation.GetRecIdFromKey_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.GetRecIdFromKey_Result> ULIMSWcfClient.svcNavValuation.Valuation_Port.GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavValuation.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ULIMSWcfClient.svcNavValuation.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavValuation.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.Create_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.Create(ULIMSWcfClient.svcNavValuation.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            ULIMSWcfClient.svcNavValuation.Create inValue = new ULIMSWcfClient.svcNavValuation.Create();
            inValue.Valuation = Valuation;
            ULIMSWcfClient.svcNavValuation.Create_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).Create(inValue);
            Valuation = retVal.Valuation;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Create_Result> CreateAsync(ULIMSWcfClient.svcNavValuation.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.CreateMultiple_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.CreateMultiple(ULIMSWcfClient.svcNavValuation.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List) {
            ULIMSWcfClient.svcNavValuation.CreateMultiple inValue = new ULIMSWcfClient.svcNavValuation.CreateMultiple();
            inValue.Valuation_List = Valuation_List;
            ULIMSWcfClient.svcNavValuation.CreateMultiple_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).CreateMultiple(inValue);
            Valuation_List = retVal.Valuation_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavValuation.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.Update_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.Update(ULIMSWcfClient.svcNavValuation.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ULIMSWcfClient.svcNavValuation.Valuation Valuation) {
            ULIMSWcfClient.svcNavValuation.Update inValue = new ULIMSWcfClient.svcNavValuation.Update();
            inValue.Valuation = Valuation;
            ULIMSWcfClient.svcNavValuation.Update_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).Update(inValue);
            Valuation = retVal.Valuation;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavValuation.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.UpdateMultiple_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.UpdateMultiple(ULIMSWcfClient.svcNavValuation.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ULIMSWcfClient.svcNavValuation.Valuation[] Valuation_List) {
            ULIMSWcfClient.svcNavValuation.UpdateMultiple inValue = new ULIMSWcfClient.svcNavValuation.UpdateMultiple();
            inValue.Valuation_List = Valuation_List;
            ULIMSWcfClient.svcNavValuation.UpdateMultiple_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).UpdateMultiple(inValue);
            Valuation_List = retVal.Valuation_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavValuation.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavValuation.Delete_Result ULIMSWcfClient.svcNavValuation.Valuation_Port.Delete(ULIMSWcfClient.svcNavValuation.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ULIMSWcfClient.svcNavValuation.Delete inValue = new ULIMSWcfClient.svcNavValuation.Delete();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavValuation.Delete_Result retVal = ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Delete_Result> ULIMSWcfClient.svcNavValuation.Valuation_Port.DeleteAsync(ULIMSWcfClient.svcNavValuation.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavValuation.Delete_Result> DeleteAsync(string Key) {
            ULIMSWcfClient.svcNavValuation.Delete inValue = new ULIMSWcfClient.svcNavValuation.Delete();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavValuation.Valuation_Port)(this)).DeleteAsync(inValue);
        }
    }
}
