//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULIMSWcfClient.svcNavApplicationForPurchase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", ConfigurationName="svcNavApplicationForPurchase.Application_For_Purchase_Port")]
    public interface Application_For_Purchase_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Read_Result Read(ULIMSWcfClient.svcNavApplicationForPurchase.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Read_Result> ReadAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId_Result ReadByRecId(ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId_Result> ReadByRecIdAsync(ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple_Result ReadMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated_Result IsUpdated(ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated_Result> IsUpdatedAsync(ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey_Result GetRecIdFromKey(ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Create_Result Create(ULIMSWcfClient.svcNavApplicationForPurchase.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Create_Result> CreateAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple_Result CreateMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Update_Result Update(ULIMSWcfClient.svcNavApplicationForPurchase.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple_Result UpdateMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Delete_Result Delete(ULIMSWcfClient.svcNavApplicationForPurchase.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/application_for_purchase:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Delete_Result> DeleteAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase")]
    public partial class Application_For_Purchase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string application_IDField;
        
        private string stand_NoField;
        
        private decimal minimum_Building_ValueField;
        
        private bool minimum_Building_ValueFieldSpecified;
        
        private decimal fixed_PropertyField;
        
        private bool fixed_PropertyFieldSpecified;
        
        private decimal purchase_PriceField;
        
        private bool purchase_PriceFieldSpecified;
        
        private System.DateTime start_DateField;
        
        private bool start_DateFieldSpecified;
        
        private System.DateTime end_DateField;
        
        private bool end_DateFieldSpecified;
        
        private string applicant_NameField;
        
        private string postal_AddressField;
        
        private string physical_AddressField;
        
        private string phone_NodField;
        
        private string iD_NoField;
        
        private string emailField;
        
        private string application_TypeField;
        
        private string user_IDField;
        
        private Payment_Method payment_MethodField;
        
        private bool payment_MethodFieldSpecified;
        
        private string update_to_FinanceField;
        
        private string faxField;
        
        private string passport_NoField;
        
        private string websiteField;
        
        private decimal depositField;
        
        private bool depositFieldSpecified;
        
        private System.DateTime installment_StartField;
        
        private bool installment_StartFieldSpecified;
        
        private int interest_RateField;
        
        private bool interest_RateFieldSpecified;
        
        private System.DateTime purchase_DateField;
        
        private bool purchase_DateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Application_ID {
            get {
                return this.application_IDField;
            }
            set {
                this.application_IDField = value;
                this.RaisePropertyChanged("Application_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Stand_No {
            get {
                return this.stand_NoField;
            }
            set {
                this.stand_NoField = value;
                this.RaisePropertyChanged("Stand_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Minimum_Building_Value {
            get {
                return this.minimum_Building_ValueField;
            }
            set {
                this.minimum_Building_ValueField = value;
                this.RaisePropertyChanged("Minimum_Building_Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Minimum_Building_ValueSpecified {
            get {
                return this.minimum_Building_ValueFieldSpecified;
            }
            set {
                this.minimum_Building_ValueFieldSpecified = value;
                this.RaisePropertyChanged("Minimum_Building_ValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Fixed_Property {
            get {
                return this.fixed_PropertyField;
            }
            set {
                this.fixed_PropertyField = value;
                this.RaisePropertyChanged("Fixed_Property");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fixed_PropertySpecified {
            get {
                return this.fixed_PropertyFieldSpecified;
            }
            set {
                this.fixed_PropertyFieldSpecified = value;
                this.RaisePropertyChanged("Fixed_PropertySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Purchase_Price {
            get {
                return this.purchase_PriceField;
            }
            set {
                this.purchase_PriceField = value;
                this.RaisePropertyChanged("Purchase_Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purchase_PriceSpecified {
            get {
                return this.purchase_PriceFieldSpecified;
            }
            set {
                this.purchase_PriceFieldSpecified = value;
                this.RaisePropertyChanged("Purchase_PriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime Start_Date {
            get {
                return this.start_DateField;
            }
            set {
                this.start_DateField = value;
                this.RaisePropertyChanged("Start_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Start_DateSpecified {
            get {
                return this.start_DateFieldSpecified;
            }
            set {
                this.start_DateFieldSpecified = value;
                this.RaisePropertyChanged("Start_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime End_Date {
            get {
                return this.end_DateField;
            }
            set {
                this.end_DateField = value;
                this.RaisePropertyChanged("End_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool End_DateSpecified {
            get {
                return this.end_DateFieldSpecified;
            }
            set {
                this.end_DateFieldSpecified = value;
                this.RaisePropertyChanged("End_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Applicant_Name {
            get {
                return this.applicant_NameField;
            }
            set {
                this.applicant_NameField = value;
                this.RaisePropertyChanged("Applicant_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Postal_Address {
            get {
                return this.postal_AddressField;
            }
            set {
                this.postal_AddressField = value;
                this.RaisePropertyChanged("Postal_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Physical_Address {
            get {
                return this.physical_AddressField;
            }
            set {
                this.physical_AddressField = value;
                this.RaisePropertyChanged("Physical_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Phone_Nod {
            get {
                return this.phone_NodField;
            }
            set {
                this.phone_NodField = value;
                this.RaisePropertyChanged("Phone_Nod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ID_No {
            get {
                return this.iD_NoField;
            }
            set {
                this.iD_NoField = value;
                this.RaisePropertyChanged("ID_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Application_Type {
            get {
                return this.application_TypeField;
            }
            set {
                this.application_TypeField = value;
                this.RaisePropertyChanged("Application_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
                this.RaisePropertyChanged("User_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Payment_Method Payment_Method {
            get {
                return this.payment_MethodField;
            }
            set {
                this.payment_MethodField = value;
                this.RaisePropertyChanged("Payment_Method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payment_MethodSpecified {
            get {
                return this.payment_MethodFieldSpecified;
            }
            set {
                this.payment_MethodFieldSpecified = value;
                this.RaisePropertyChanged("Payment_MethodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Update_to_Finance {
            get {
                return this.update_to_FinanceField;
            }
            set {
                this.update_to_FinanceField = value;
                this.RaisePropertyChanged("Update_to_Finance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Passport_No {
            get {
                return this.passport_NoField;
            }
            set {
                this.passport_NoField = value;
                this.RaisePropertyChanged("Passport_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("Website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal Deposit {
            get {
                return this.depositField;
            }
            set {
                this.depositField = value;
                this.RaisePropertyChanged("Deposit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepositSpecified {
            get {
                return this.depositFieldSpecified;
            }
            set {
                this.depositFieldSpecified = value;
                this.RaisePropertyChanged("DepositSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=22)]
        public System.DateTime Installment_Start {
            get {
                return this.installment_StartField;
            }
            set {
                this.installment_StartField = value;
                this.RaisePropertyChanged("Installment_Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Installment_StartSpecified {
            get {
                return this.installment_StartFieldSpecified;
            }
            set {
                this.installment_StartFieldSpecified = value;
                this.RaisePropertyChanged("Installment_StartSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int Interest_Rate {
            get {
                return this.interest_RateField;
            }
            set {
                this.interest_RateField = value;
                this.RaisePropertyChanged("Interest_Rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Interest_RateSpecified {
            get {
                return this.interest_RateFieldSpecified;
            }
            set {
                this.interest_RateFieldSpecified = value;
                this.RaisePropertyChanged("Interest_RateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=24)]
        public System.DateTime Purchase_Date {
            get {
                return this.purchase_DateField;
            }
            set {
                this.purchase_DateField = value;
                this.RaisePropertyChanged("Purchase_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purchase_DateSpecified {
            get {
                return this.purchase_DateFieldSpecified;
            }
            set {
                this.purchase_DateFieldSpecified = value;
                this.RaisePropertyChanged("Purchase_DateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase")]
    public enum Payment_Method {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Cash,
        
        /// <remarks/>
        Installment,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase")]
    public partial class Application_For_Purchase_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Application_For_Purchase_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Application_For_Purchase_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase")]
    public enum Application_For_Purchase_Fields {
        
        /// <remarks/>
        Application_ID,
        
        /// <remarks/>
        Stand_No,
        
        /// <remarks/>
        Minimum_Building_Value,
        
        /// <remarks/>
        Fixed_Property,
        
        /// <remarks/>
        Purchase_Price,
        
        /// <remarks/>
        Start_Date,
        
        /// <remarks/>
        End_Date,
        
        /// <remarks/>
        Applicant_Name,
        
        /// <remarks/>
        Postal_Address,
        
        /// <remarks/>
        Physical_Address,
        
        /// <remarks/>
        Phone_Nod,
        
        /// <remarks/>
        ID_No,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Application_Type,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Payment_Method,
        
        /// <remarks/>
        Update_to_Finance,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Passport_No,
        
        /// <remarks/>
        Website,
        
        /// <remarks/>
        Deposit,
        
        /// <remarks/>
        Installment_Start,
        
        /// <remarks/>
        Interest_Rate,
        
        /// <remarks/>
        Purchase_Date,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public string Application_ID;
        
        public Read() {
        }
        
        public Read(string Application_ID) {
            this.Application_ID = Application_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase;
        
        public Read_Result() {
        }
        
        public Read_Result(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            this.Application_For_Purchase = Application_For_Purchase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            this.Application_For_Purchase = Application_For_Purchase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase;
        
        public Create() {
        }
        
        public Create(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            this.Application_For_Purchase = Application_For_Purchase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase;
        
        public Create_Result() {
        }
        
        public Create_Result(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            this.Application_For_Purchase = Application_For_Purchase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List) {
            this.Application_For_Purchase_List = Application_For_Purchase_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List) {
            this.Application_For_Purchase_List = Application_For_Purchase_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase;
        
        public Update() {
        }
        
        public Update(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            this.Application_For_Purchase = Application_For_Purchase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase;
        
        public Update_Result() {
        }
        
        public Update_Result(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            this.Application_For_Purchase = Application_For_Purchase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List) {
            this.Application_For_Purchase_List = Application_For_Purchase_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List) {
            this.Application_For_Purchase_List = Application_For_Purchase_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/application_for_purchase", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Application_For_Purchase_PortChannel : ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Application_For_Purchase_PortClient : System.ServiceModel.ClientBase<ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port>, ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port {
        
        public Application_For_Purchase_PortClient() {
        }
        
        public Application_For_Purchase_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Application_For_Purchase_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Application_For_Purchase_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Application_For_Purchase_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Read_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.Read(ULIMSWcfClient.svcNavApplicationForPurchase.Read request) {
            return base.Channel.Read(request);
        }
        
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Read(string Application_ID) {
            ULIMSWcfClient.svcNavApplicationForPurchase.Read inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.Read();
            inValue.Application_ID = Application_ID;
            ULIMSWcfClient.svcNavApplicationForPurchase.Read_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).Read(inValue);
            return retVal.Application_For_Purchase;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Read_Result> ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.ReadAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Read_Result> ReadAsync(string Application_ID) {
            ULIMSWcfClient.svcNavApplicationForPurchase.Read inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.Read();
            inValue.Application_ID = Application_ID;
            return ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.ReadByRecId(ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase ReadByRecId(string recId) {
            ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId();
            inValue.recId = recId;
            ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).ReadByRecId(inValue);
            return retVal.Application_For_Purchase;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId_Result> ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.ReadByRecIdAsync(ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.ReadByRecId();
            inValue.recId = recId;
            return ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.ReadMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] ReadMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple_Result> ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.ReadMultipleAsync(ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.IsUpdated(ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated_Result> ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.IsUpdatedAsync(ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.IsUpdated();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.GetRecIdFromKey(ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey_Result> ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Create_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.Create(ULIMSWcfClient.svcNavApplicationForPurchase.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            ULIMSWcfClient.svcNavApplicationForPurchase.Create inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.Create();
            inValue.Application_For_Purchase = Application_For_Purchase;
            ULIMSWcfClient.svcNavApplicationForPurchase.Create_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).Create(inValue);
            Application_For_Purchase = retVal.Application_For_Purchase;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Create_Result> CreateAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.CreateMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List) {
            ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple();
            inValue.Application_For_Purchase_List = Application_For_Purchase_List;
            ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).CreateMultiple(inValue);
            Application_For_Purchase_List = retVal.Application_For_Purchase_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavApplicationForPurchase.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Update_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.Update(ULIMSWcfClient.svcNavApplicationForPurchase.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase Application_For_Purchase) {
            ULIMSWcfClient.svcNavApplicationForPurchase.Update inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.Update();
            inValue.Application_For_Purchase = Application_For_Purchase;
            ULIMSWcfClient.svcNavApplicationForPurchase.Update_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).Update(inValue);
            Application_For_Purchase = retVal.Application_For_Purchase;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.UpdateMultiple(ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase[] Application_For_Purchase_List) {
            ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple();
            inValue.Application_For_Purchase_List = Application_For_Purchase_List;
            ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).UpdateMultiple(inValue);
            Application_For_Purchase_List = retVal.Application_For_Purchase_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavApplicationForPurchase.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavApplicationForPurchase.Delete_Result ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.Delete(ULIMSWcfClient.svcNavApplicationForPurchase.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ULIMSWcfClient.svcNavApplicationForPurchase.Delete inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.Delete();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavApplicationForPurchase.Delete_Result retVal = ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Delete_Result> ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port.DeleteAsync(ULIMSWcfClient.svcNavApplicationForPurchase.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavApplicationForPurchase.Delete_Result> DeleteAsync(string Key) {
            ULIMSWcfClient.svcNavApplicationForPurchase.Delete inValue = new ULIMSWcfClient.svcNavApplicationForPurchase.Delete();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavApplicationForPurchase.Application_For_Purchase_Port)(this)).DeleteAsync(inValue);
        }
    }
}
