//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULIMSWcfClient.svcNavErfs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", ConfigurationName="svcNavErfs.Erfs_Port")]
    public interface Erfs_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.Read_Result Read(ULIMSWcfClient.svcNavErfs.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Read_Result> ReadAsync(ULIMSWcfClient.svcNavErfs.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.ReadByRecId_Result ReadByRecId(ULIMSWcfClient.svcNavErfs.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.ReadByRecId_Result> ReadByRecIdAsync(ULIMSWcfClient.svcNavErfs.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.ReadMultiple_Result ReadMultiple(ULIMSWcfClient.svcNavErfs.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavErfs.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.IsUpdated_Result IsUpdated(ULIMSWcfClient.svcNavErfs.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.IsUpdated_Result> IsUpdatedAsync(ULIMSWcfClient.svcNavErfs.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.GetRecIdFromKey_Result GetRecIdFromKey(ULIMSWcfClient.svcNavErfs.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavErfs.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.Create_Result Create(ULIMSWcfClient.svcNavErfs.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Create_Result> CreateAsync(ULIMSWcfClient.svcNavErfs.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.CreateMultiple_Result CreateMultiple(ULIMSWcfClient.svcNavErfs.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavErfs.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.Update_Result Update(ULIMSWcfClient.svcNavErfs.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavErfs.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.UpdateMultiple_Result UpdateMultiple(ULIMSWcfClient.svcNavErfs.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavErfs.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ULIMSWcfClient.svcNavErfs.Delete_Result Delete(ULIMSWcfClient.svcNavErfs.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/erfs:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Delete_Result> DeleteAsync(ULIMSWcfClient.svcNavErfs.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs")]
    public partial class Erfs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string stand_NoField;
        
        private string erf_NoField;
        
        private string street_AddressField;
        
        private string townshipField;
        
        private string local_AuthorityField;
        
        private string zoningField;
        
        private decimal sizeField;
        
        private bool sizeFieldSpecified;
        
        private string gis_ParentField;
        
        private string gis_CommentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Stand_No {
            get {
                return this.stand_NoField;
            }
            set {
                this.stand_NoField = value;
                this.RaisePropertyChanged("Stand_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Erf_No {
            get {
                return this.erf_NoField;
            }
            set {
                this.erf_NoField = value;
                this.RaisePropertyChanged("Erf_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street_Address {
            get {
                return this.street_AddressField;
            }
            set {
                this.street_AddressField = value;
                this.RaisePropertyChanged("Street_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Township {
            get {
                return this.townshipField;
            }
            set {
                this.townshipField = value;
                this.RaisePropertyChanged("Township");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Local_Authority {
            get {
                return this.local_AuthorityField;
            }
            set {
                this.local_AuthorityField = value;
                this.RaisePropertyChanged("Local_Authority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Zoning {
            get {
                return this.zoningField;
            }
            set {
                this.zoningField = value;
                this.RaisePropertyChanged("Zoning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Gis_Parent {
            get {
                return this.gis_ParentField;
            }
            set {
                this.gis_ParentField = value;
                this.RaisePropertyChanged("Gis_Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Gis_Comment {
            get {
                return this.gis_CommentField;
            }
            set {
                this.gis_CommentField = value;
                this.RaisePropertyChanged("Gis_Comment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs")]
    public partial class Erfs_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Erfs_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Erfs_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs")]
    public enum Erfs_Fields {
        
        /// <remarks/>
        Stand_No,
        
        /// <remarks/>
        Erf_No,
        
        /// <remarks/>
        Street_Address,
        
        /// <remarks/>
        Township,
        
        /// <remarks/>
        Local_Authority,
        
        /// <remarks/>
        Zoning,
        
        /// <remarks/>
        Size,
        
        /// <remarks/>
        Gis_Parent,
        
        /// <remarks/>
        Gis_Comment,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public string Stand_No;
        
        public Read() {
        }
        
        public Read(string Stand_No) {
            this.Stand_No = Stand_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public ULIMSWcfClient.svcNavErfs.Erfs Erfs;
        
        public Read_Result() {
        }
        
        public Read_Result(ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            this.Erfs = Erfs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public ULIMSWcfClient.svcNavErfs.Erfs Erfs;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            this.Erfs = Erfs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ULIMSWcfClient.svcNavErfs.Erfs_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ULIMSWcfClient.svcNavErfs.Erfs_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavErfs.Erfs[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ULIMSWcfClient.svcNavErfs.Erfs[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public ULIMSWcfClient.svcNavErfs.Erfs Erfs;
        
        public Create() {
        }
        
        public Create(ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            this.Erfs = Erfs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public ULIMSWcfClient.svcNavErfs.Erfs Erfs;
        
        public Create_Result() {
        }
        
        public Create_Result(ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            this.Erfs = Erfs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List) {
            this.Erfs_List = Erfs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List) {
            this.Erfs_List = Erfs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public ULIMSWcfClient.svcNavErfs.Erfs Erfs;
        
        public Update() {
        }
        
        public Update(ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            this.Erfs = Erfs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public ULIMSWcfClient.svcNavErfs.Erfs Erfs;
        
        public Update_Result() {
        }
        
        public Update_Result(ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            this.Erfs = Erfs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List) {
            this.Erfs_List = Erfs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List) {
            this.Erfs_List = Erfs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/erfs", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/erfs", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Erfs_PortChannel : ULIMSWcfClient.svcNavErfs.Erfs_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Erfs_PortClient : System.ServiceModel.ClientBase<ULIMSWcfClient.svcNavErfs.Erfs_Port>, ULIMSWcfClient.svcNavErfs.Erfs_Port {
        
        public Erfs_PortClient() {
        }
        
        public Erfs_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Erfs_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Erfs_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Erfs_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.Read_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.Read(ULIMSWcfClient.svcNavErfs.Read request) {
            return base.Channel.Read(request);
        }
        
        public ULIMSWcfClient.svcNavErfs.Erfs Read(string Stand_No) {
            ULIMSWcfClient.svcNavErfs.Read inValue = new ULIMSWcfClient.svcNavErfs.Read();
            inValue.Stand_No = Stand_No;
            ULIMSWcfClient.svcNavErfs.Read_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).Read(inValue);
            return retVal.Erfs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Read_Result> ULIMSWcfClient.svcNavErfs.Erfs_Port.ReadAsync(ULIMSWcfClient.svcNavErfs.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Read_Result> ReadAsync(string Stand_No) {
            ULIMSWcfClient.svcNavErfs.Read inValue = new ULIMSWcfClient.svcNavErfs.Read();
            inValue.Stand_No = Stand_No;
            return ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.ReadByRecId_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.ReadByRecId(ULIMSWcfClient.svcNavErfs.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ULIMSWcfClient.svcNavErfs.Erfs ReadByRecId(string recId) {
            ULIMSWcfClient.svcNavErfs.ReadByRecId inValue = new ULIMSWcfClient.svcNavErfs.ReadByRecId();
            inValue.recId = recId;
            ULIMSWcfClient.svcNavErfs.ReadByRecId_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).ReadByRecId(inValue);
            return retVal.Erfs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.ReadByRecId_Result> ULIMSWcfClient.svcNavErfs.Erfs_Port.ReadByRecIdAsync(ULIMSWcfClient.svcNavErfs.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ULIMSWcfClient.svcNavErfs.ReadByRecId inValue = new ULIMSWcfClient.svcNavErfs.ReadByRecId();
            inValue.recId = recId;
            return ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.ReadMultiple_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.ReadMultiple(ULIMSWcfClient.svcNavErfs.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ULIMSWcfClient.svcNavErfs.Erfs[] ReadMultiple(ULIMSWcfClient.svcNavErfs.Erfs_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavErfs.ReadMultiple inValue = new ULIMSWcfClient.svcNavErfs.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ULIMSWcfClient.svcNavErfs.ReadMultiple_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.ReadMultiple_Result> ULIMSWcfClient.svcNavErfs.Erfs_Port.ReadMultipleAsync(ULIMSWcfClient.svcNavErfs.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.ReadMultiple_Result> ReadMultipleAsync(ULIMSWcfClient.svcNavErfs.Erfs_Filter[] filter, string bookmarkKey, int setSize) {
            ULIMSWcfClient.svcNavErfs.ReadMultiple inValue = new ULIMSWcfClient.svcNavErfs.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.IsUpdated_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.IsUpdated(ULIMSWcfClient.svcNavErfs.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ULIMSWcfClient.svcNavErfs.IsUpdated inValue = new ULIMSWcfClient.svcNavErfs.IsUpdated();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavErfs.IsUpdated_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.IsUpdated_Result> ULIMSWcfClient.svcNavErfs.Erfs_Port.IsUpdatedAsync(ULIMSWcfClient.svcNavErfs.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ULIMSWcfClient.svcNavErfs.IsUpdated inValue = new ULIMSWcfClient.svcNavErfs.IsUpdated();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.GetRecIdFromKey_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.GetRecIdFromKey(ULIMSWcfClient.svcNavErfs.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ULIMSWcfClient.svcNavErfs.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavErfs.GetRecIdFromKey();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavErfs.GetRecIdFromKey_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.GetRecIdFromKey_Result> ULIMSWcfClient.svcNavErfs.Erfs_Port.GetRecIdFromKeyAsync(ULIMSWcfClient.svcNavErfs.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ULIMSWcfClient.svcNavErfs.GetRecIdFromKey inValue = new ULIMSWcfClient.svcNavErfs.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.Create_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.Create(ULIMSWcfClient.svcNavErfs.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            ULIMSWcfClient.svcNavErfs.Create inValue = new ULIMSWcfClient.svcNavErfs.Create();
            inValue.Erfs = Erfs;
            ULIMSWcfClient.svcNavErfs.Create_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).Create(inValue);
            Erfs = retVal.Erfs;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Create_Result> CreateAsync(ULIMSWcfClient.svcNavErfs.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.CreateMultiple_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.CreateMultiple(ULIMSWcfClient.svcNavErfs.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List) {
            ULIMSWcfClient.svcNavErfs.CreateMultiple inValue = new ULIMSWcfClient.svcNavErfs.CreateMultiple();
            inValue.Erfs_List = Erfs_List;
            ULIMSWcfClient.svcNavErfs.CreateMultiple_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).CreateMultiple(inValue);
            Erfs_List = retVal.Erfs_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.CreateMultiple_Result> CreateMultipleAsync(ULIMSWcfClient.svcNavErfs.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.Update_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.Update(ULIMSWcfClient.svcNavErfs.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ULIMSWcfClient.svcNavErfs.Erfs Erfs) {
            ULIMSWcfClient.svcNavErfs.Update inValue = new ULIMSWcfClient.svcNavErfs.Update();
            inValue.Erfs = Erfs;
            ULIMSWcfClient.svcNavErfs.Update_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).Update(inValue);
            Erfs = retVal.Erfs;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Update_Result> UpdateAsync(ULIMSWcfClient.svcNavErfs.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.UpdateMultiple_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.UpdateMultiple(ULIMSWcfClient.svcNavErfs.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ULIMSWcfClient.svcNavErfs.Erfs[] Erfs_List) {
            ULIMSWcfClient.svcNavErfs.UpdateMultiple inValue = new ULIMSWcfClient.svcNavErfs.UpdateMultiple();
            inValue.Erfs_List = Erfs_List;
            ULIMSWcfClient.svcNavErfs.UpdateMultiple_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).UpdateMultiple(inValue);
            Erfs_List = retVal.Erfs_List;
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.UpdateMultiple_Result> UpdateMultipleAsync(ULIMSWcfClient.svcNavErfs.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULIMSWcfClient.svcNavErfs.Delete_Result ULIMSWcfClient.svcNavErfs.Erfs_Port.Delete(ULIMSWcfClient.svcNavErfs.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ULIMSWcfClient.svcNavErfs.Delete inValue = new ULIMSWcfClient.svcNavErfs.Delete();
            inValue.Key = Key;
            ULIMSWcfClient.svcNavErfs.Delete_Result retVal = ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Delete_Result> ULIMSWcfClient.svcNavErfs.Erfs_Port.DeleteAsync(ULIMSWcfClient.svcNavErfs.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULIMSWcfClient.svcNavErfs.Delete_Result> DeleteAsync(string Key) {
            ULIMSWcfClient.svcNavErfs.Delete inValue = new ULIMSWcfClient.svcNavErfs.Delete();
            inValue.Key = Key;
            return ((ULIMSWcfClient.svcNavErfs.Erfs_Port)(this)).DeleteAsync(inValue);
        }
    }
}
